### ISSUE TITLE
500 when Custodian invites existing admin to be a custodian (on staging)

### ISSUE THREAD

**Issue by gidsg** [openregister/managing-registers#107]
*Note this only occurs on staging, not on localhost*

## Steps to reproduce
* Go to: https://managing-registers-staging.cloudapps.digital
* Log in as a Custodian
* Click 'Manage Team'
* Invite existing admin email address to your team 
* Enter email and choose either permissions 'Advanced' or 'Basic'

## Actual results
500 

## Expected Results
Success message

### In logs:
```
   2017-10-25T09:32:53.34+0100 [APP/PROC/WEB/1] OUT I, [2017-10-25T08:32:53.339834 #73]  INFO -- : [8dda2e93-bb88-4a0e-8626-fe05bf06cb21] Completed 500 Internal Server Error in 90ms (ActiveRecord: 10.4ms)
   2017-10-25T09:32:53.34+0100 [APP/PROC/WEB/1] OUT F, [2017-10-25T08:32:53.340294 #73] FATAL -- : [8dda2e93-bb88-4a0e-8626-fe05bf06cb21]   
   2017-10-25T09:32:53.34+0100 [APP/PROC/WEB/1] OUT F, [2017-10-25T08:32:53.340368 #73] FATAL -- : [8dda2e93-bb88-4a0e-8626-fe05bf06cb21] Notifications::Client::RequestError ([{"error"=>"BadRequestError", "message"=>"Missing personalisation: registers"}]):
   2017-10-25T09:32:53.34+0100 [APP/PROC/WEB/1] OUT F, [2017-10-25T08:32:53.340425 #73] FATAL -- : [8dda2e93-bb88-4a0e-8626-fe05bf06cb21]   
   2017-10-25T09:32:53.34+0100 [APP/PROC/WEB/1] OUT F, [2017-10-25T08:32:53.340501 #73] FATAL -- : [8dda2e93-bb88-4a0e-8626-fe05bf06cb21] app/models/user.rb:50:in `send_devise_notification'
   2017-10-25T09:32:53.34+0100 [APP/PROC/WEB/1] OUT [8dda2e93-bb88-4a0e-8626-fe05bf06cb21] app/controllers/users_controller.rb:102:in `invite_resource'
```

**Comment by gidsg** [comment]
Is this an allowed case where an admin can also be a custodian?
