### ISSUE TITLE
Admin cannot manage the register 'Register'

### ISSUE THREAD

**Issue by fjavierm** [openregister/managing-registers#124]
When an admin tries to manage a register, the application throws an error.

**URL**
https://managing-registers-staging.cloudapps.digital/register

**Steps to reproduce**
1. Log as admin
2. Click in the 'Register' link.

**Actual result**
Error page: We're sorry, but something went wrong.

**Expected**
To see the register Register records.

Note: Maybe just a data problem. It happens in staging and locally.

`
2017-10-27T09:08:31.33+0100 [RTR/1] OUT 
   2017-10-27T09:08:31.33+0100 [APP/PROC/WEB/1] OUT I, [2017-10-27T08:08:31.337083 #69]  INFO -- : [dd310a48-290c-45d9-b387-8091315ceb6f] Completed 500 Internal Server Error in 1252ms (ActiveRecord: 0.9ms)
   2017-10-27T09:08:31.33+0100 [APP/PROC/WEB/1] OUT F, [2017-10-27T08:08:31.337622 #69] FATAL -- : [dd310a48-290c-45d9-b387-8091315ceb6f]   
   2017-10-27T09:08:31.33+0100 [APP/PROC/WEB/1] OUT F, [2017-10-27T08:08:31.337688 #69] FATAL -- : [dd310a48-290c-45d9-b387-8091315ceb6f] ArgumentError (comparison of String with nil failed):
   2017-10-27T09:08:31.33+0100 [APP/PROC/WEB/1] OUT F, [2017-10-27T08:08:31.337738 #69] FATAL -- : [dd310a48-290c-45d9-b387-8091315ceb6f]   
   2017-10-27T09:08:31.33+0100 [APP/PROC/WEB/1] OUT F, [2017-10-27T08:08:31.337799 #69] FATAL -- : [dd310a48-290c-45d9-b387-8091315ceb6f] app/controllers/register_controller.rb:13:in `sort_by'
   2017-10-27T09:08:31.33+0100 [APP/PROC/WEB/1] OUT [dd310a48-290c-45d9-b387-8091315ceb6f] app/controllers/register_controller.rb:13:in `index'
`

/cc @Maidment64

**Comment by arnau** [comment]
@fjavierm do you know if it's a recent regression?

**Comment by fjavierm** [comment]
@arnau I haven't done any investigation, I was trying to do something else. I've raised the issue to take a look in some point

**Comment by gidsg** [comment]
We decided users should not be able to edit the 'Register' register and it has been filtered out, so this issue can be closed.
