### ISSUE TITLE
Update custodian send invite page error

### ISSUE THREAD

**Issue by fjavierm** [openregister/managing-registers#125]
Application throws an error
**URL**
https://managing-registers-staging.cloudapps.digital/users/invitation/new?team_id=15

**Steps to reproduce**
1. Log as admin
2. Click in link above
3. Insert email
4. Click 'Send invite'

**Actual result**
Application is crashing

**Expected result**
Application should send the invitation

`
2017-10-27T10:09:27.15+0100 [APP/PROC/WEB/1] OUT D, [2017-10-27T09:09:27.151863 #70] DEBUG -- : [1f3978b7-eeb2-45f8-8f55-9a5f482416ad] DeviseMailer#invitation_instructions: processed outbound mail in 3.7ms
   2017-10-27T10:09:27.15+0100 [APP/PROC/WEB/1] OUT I, [2017-10-27T09:09:27.152067 #70]  INFO -- : [1f3978b7-eeb2-45f8-8f55-9a5f482416ad] Completed 500 Internal Server Error in 45ms (ActiveRecord: 26.8ms)
   2017-10-27T10:09:27.15+0100 [APP/PROC/WEB/1] OUT F, [2017-10-27T09:09:27.152570 #70] FATAL -- : [1f3978b7-eeb2-45f8-8f55-9a5f482416ad]   
   2017-10-27T10:09:27.15+0100 [APP/PROC/WEB/1] OUT F, [2017-10-27T09:09:27.152647 #70] FATAL -- : [1f3978b7-eeb2-45f8-8f55-9a5f482416ad] ArgumentError (Missing template ID. Make sure to use `set_template` before calling `mail`):
   2017-10-27T10:09:27.15+0100 [APP/PROC/WEB/1] OUT F, [2017-10-27T09:09:27.152704 #70] FATAL -- : [1f3978b7-eeb2-45f8-8f55-9a5f482416ad]   
   2017-10-27T10:09:27.15+0100 [APP/PROC/WEB/1] OUT F, [2017-10-27T09:09:27.152761 #70] FATAL -- : [1f3978b7-eeb2-45f8-8f55-9a5f482416ad] app/mailers/devise_mailer.rb:47:in `invitation_instructions'
   2017-10-27T10:09:27.15+0100 [APP/PROC/WEB/1] OUT [1f3978b7-eeb2-45f8-8f55-9a5f482416ad] app/models/user.rb:50:in `send_devise_notification'
   2017-10-27T10:09:27.15+0100 [APP/PROC/WEB/1] OUT [1f3978b7-eeb2-45f8-8f55-9a5f482416ad] app/controllers/users_controller.rb:117:in `invite_resource'
   2017-10-27T10:09:27.15+0100 [APP/PROC/WEB/1] OUT [1f3978b7-eeb2-45f8-8f55-9a5f482416ad] app/controllers/users_controller.rb:65:in `create'
`

/cc @Maidment64

**Comment by fjavierm** [comment]
The URL is not accessible any more. Admin is just able to invite other admins or custodians, not users to the teams.
